import Head from "next/head";
import Image from "next/image";

// components imports
import Header from "../components/Header";
import Container from "../components/Container";
import FeaturedProduct from "../components/FeaturedProduct";
import ProductsList from "../components/ProductsList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container>
          <FeaturedProduct />
          <ProductsList />
        </Container>
      </main>
    </div>
  );
}
