import Head from "next/head";
import Image from "next/image";

// components imports
import Header from "../components/Header";
import Container from "../components/Container";
import FeaturedProduct from "../components/FeaturedProduct";
import ProductsList from "../components/ProductsList";

// mock data imports
import { products } from "../data/products.js";

export default function Home() {
  const featuredProduct = products.find((product) => product.featured);
  const nonFeaturedProducts = products.filter((product) => !product.featured);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container>
          <FeaturedProduct featuredProduct={featuredProduct} />
          <ProductsList products={nonFeaturedProducts} />
        </Container>
      </main>
    </div>
  );
}
